# Config file for Air live reloading for Go
# See https://github.com/cosmtrek/air for more options

[build]
  # Working directory
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main ."
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", "vendor"]
  exclude_file = []
  follow_symlink = true
  # Delay before restart (ms)
  delay = 1000

[log]
  time = true

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"

[run]
  cmd = "./tmp/main"
  watch_dir = "."
  watch_ext = ["go", "tpl", "tmpl", "html"]
  ignore_dir = ["assets", "tmp", "vendor"]
  ignore_file = []
  grace_time = 500
